# Generated by Django 5.1.4 on 2024-12-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_material_name_alter_material_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='has_failure',
            field=models.BooleanField(default=False),
        ),
    ]
